FROM node:18-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app


COPY . .
RUN yarn config set registry https://registry.npm.taobao.org/
RUN yarn config set sentrycli_cdnurl https://npmmirror.com/mirrors/sentry-cli/
#RUN yarn --update-checksums
RUN yarn global add turbo
# RUN yarn add sentry-cli  --registry=https://cdn.npm.taobao.org/dist/sentry-cli
#RUN npm set ENTRYCLI_CDNURL=https://cdn.npm.taobao.org/dist/sentry-cli
#RUN npm set sentrycli_cdnurl=https://cdn.npm.taobao.org/dist/sentry-cli

#RUN yarn install --network-timeout 500000 --silent 2>&1 >/dev/null | grep "error"

RUN yarn install --network-timeout 500000 --severity error

EXPOSE 3000
CMD ["yarn","dev", "--filter=space"]
